### PR TITLE
Release v0.17.0

### PR DESCRIPTION
**Pull request by sphuber**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sphuber** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
@sphuber please don't forget to update the dependencies 
https://github.com/aiidateam/plumpy/blob/06c8e06cf2eebdf68e8d9dcc1272f6d7ce061518/setup.py#L32-L35

**Comment by sphuber** [comment]
@ltalirz But the dependencies haven't changed since 0.16.0 ....

**Comment by ltalirz** [comment]
@sphuber You may remember that we released 0.15.1 last on conda-forge (as you can see from the diff of the PR)

In any case, a quick look into the setup.py that I linked for you will show you that the dependencies are out of date

**Comment by sphuber** [comment]
Yeah I just remembered how this conda thingy works. Forgot that we "reverted" master to older version to get it released.

**Comment by ltalirz** [comment]
For the python version, see e.g. https://github.com/conda-forge/aiida-core-feedstock/blob/master/recipe/meta.yaml#L24

**Pull request merged**
