### PR TITLE
Bump the build number

### PR DESCRIPTION
**Pull request by sphuber**
This is to trigger a new build for v0.17.1 which failed for Linux.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sphuber** [comment]
@conda-forge-admin, please rerender

**Comment by sphuber** [comment]
@ltalirz linux build failed again, but this time because it failed to download the .tar.gz source of pypi.org Not sure if that was the original failure of the build as well or if this is just bad luck

**Comment by ltalirz** [comment]
This time it was just 2 tasks that failed (before it was 4).
It looks to me like there are problems on the azure platform although the one reported here https://status.dev.azure.com/_history is probably not what we were seeing.

Could you try to force-push again?

**Comment by sphuber** [comment]
@ltalirz force-pushed and tests passed this time around

**Pull request merged**
