### PR TITLE
bump build number

### PR DESCRIPTION
**Pull request by ltalirz**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
@astamminger Perhaps I was not too clear:
This PR removes all conditions on the python version for plumpy, and I have re-rendered the feedstock multiple times. Still, for some reason no python 3.8 build shows up on the checks...

**Comment by astamminger** [comment]
Hi @ltalirz 
yes, I was thinking of a rebuild like in conda-forge/aiida-core-feedstock#22. 
I am not sure if re-rendering is doing the same thing.

**Comment by ltalirz** [comment]
Aha, I thought this was the same.
Looking at the first commit of the PR you linked, however, one can see that it did add a new file to the repo:
https://github.com/conda-forge/aiida-core-feedstock/pull/22/commits/b1b4343c40b065534db27674668c507a2e3b498b

Should we do the same manually or can one trigger this somehow?

**Comment by astamminger** [comment]
@ltalirz since python constraints were removed entirely: Why not simply add ``noarch: python`` to the recipe's build section and build a noarch package?

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
good point - done! I'll try in an hour whether that fixes the aiida-core build

**Pull request merged**
