### PR TITLE
Add build for `plumpy==0.15.1`

### PR DESCRIPTION
**Pull request by sphuber**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sphuber** [comment]
@conda-forge-admin, please rerender

**Comment by sphuber** [comment]
@conda-forge-admin, please rerender

**Review by ltalirz — COMMENTED** [review]
thanks @sphuber 

I just checked the dependencies and noticed pyyaml there
https://github.com/aiidateam/plumpy/blob/v0.15.1/setup.py

+ the kiwipy selector is a bit different.
Is this on purpose?

**Comment by sphuber** [comment]
@ltalirz it is the same as for [0.15.0](https://github.com/aiidateam/plumpy/blob/v0.15.0/setup.py) and for this PR I simply branched of the commit that built 0.15.0. The dependecies therefore should be the same

**Comment by ltalirz** [comment]
yes, they are just not the same as for the plumpy 0.15.1 release

**Comment by sphuber** [comment]
Note that we are making a release for 0.15.1 which has different requirements than 0.16.1 which is what is currently on `master`. That is why I also had to change the depencies, which correspond to those of the 0.15.0 release on this repo. Note that I remove `nest-asyncio` which is 0.16.* specific and add tornado again, which is necessary for 0.15.*

**Comment by ltalirz** [comment]
Sure, it is just that we usually try to mirror the dependencies of the pypi release on conda-forge as well.
It seems like there were some minor things missed in the plumpy 0.15.0 release; might be good to fix this as well, but we can also fix it in 0.15.1

**Comment by sphuber** [comment]
@ltalirz updated the dependencies

**Review by ltalirz — APPROVED** [review]
thanks @sphuber!

**Pull request merged**
