### PR TITLE
Release v0.17.1

### PR DESCRIPTION
**Pull request by sphuber**
This is just a release to put an upper limit on the Python version for
which `aiocontextvars` should be installed which is a backport of
`contextvars` which was added in Python 3.7.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sphuber** [comment]
@conda-forge-admin, please rerender

**Comment by sphuber** [comment]
@ltalirz @csadorf @chrisjsewell any idea what the linter is trying to say with

> Non noarch packages should have python requirement without any version constraints.

**Comment by ltalirz** [comment]
@sphuber Seems it wants you to remove this again
https://github.com/conda-forge/plumpy-feedstock/pull/42/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR25

**Comment by ltalirz** [comment]
(with remove I meant just the upper limit, sorry ;-) )

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
Wow, seems to pass @sphuber ! ;-)

**Comment by sphuber** [comment]
Is it then also ready to merge @ltalirz ? Or do we still need to adapt something?

**Comment by ltalirz** [comment]
merged :-)

**Comment by ltalirz** [comment]
Before restarting the checks on aiida-core, you can check whether the package is available (usually takes ~1h) using

```
conda -c conda-forge search plumpy==0.17.1
```

**Comment by sphuber** [comment]
> Before restarting the checks on aiida-core, you can check whether the package is available (usually takes ~1h) using
> 
> ```
> conda -c conda-forge search plumpy==0.17.1
> ```

Doesn't work :(
```
(aiida_dev) sph@bastion:~/code/aiida/env/dev/aiida-core$ conda -c conda-forge search plumpy==0.17.1

CommandNotFoundError: No command 'conda conda-forge'.
```

**Comment by csadorf** [comment]
@sphuber Maybe the `-c conda-forge` is an option to `search`?

**Comment by sphuber** [comment]
@ltalirz the new build seems to be available [judging from this conda site](https://anaconda.org/conda-forge/plumpy). However, the [build is still failing](https://github.com/aiidateam/aiida-core/pull/4317/checks?check_run_id=1454697683) because it cannot find the build. I noticed on the conda-force package list that 0.17.1 is only listed fro MacOS and Windows 64 bit. Last build for Linux is the no-arch 0.17.0 package or Linux specific the last is v0.14.5 which is super old. Any ideas why there is no v0.17.1 for Linux?

**Comment by ltalirz** [comment]
For some reason, the linux builds failed on the merge commit https://github.com/conda-forge/plumpy-feedstock/runs/1454028188 (while they worked fine on the PR).

Hm...

**Comment by ltalirz** [comment]
I don't think we can easily restart this (it would also be a bit dangerous if that was possible, since it will release the package). 
Such failures should really never happen...

Perhaps the easiest is to bump the build number to 1 and try again? If this is an intermittent issue in the runners, it will likely show up on the PR build as well

**Pull request merged**
